apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-python
  template:
    metadata:
      labels:
        app: demo-python
    spec:
      containers:
        - name: demo-python
          image: demo-devops-python:latest
          ports:
            - containerPort: 8005
